In [2]:
import unittest

import torch

from src.backends.cusparse_backend.utils import csr_SPMM_normalized

Using /home/daniilkk/.cache/torch_extensions/py311_cu121 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/daniilkk/.cache/torch_extensions/py311_cu121/cuda_kernels/build.ninja...
/home/daniilkk/repos/Accelerating-GNNs/.venv/lib/python3.11/site-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Building extension module cuda_kernels...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)


ninja: no work to do.


Loading extension module cuda_kernels...


In [3]:
indptr = torch.tensor([0, 2, 3, 5], dtype=torch.int32, device="cuda")
indices = torch.tensor([1, 2, 0, 1, 2], dtype=torch.int32, device="cuda")
features = torch.tensor([[1.0, 0.0], [0.0, 1.0], [1.0, 1.0]], dtype=torch.float32, device="cuda")
# edge_weights = torch.tensor([0.5, 1.0, 0.5, 1.0, 0.5], dtype=torch.float32, device='cuda')

result = csr_SPMM_normalized(indptr, indices, features, norm="none", algorithm=3, use_cache=False, do_transpose_a=False)
# expected = torch.tensor([[1., 2.], [1., 0.], [1., 2.]], dtype=torch.float32, device='cuda')
# torch.testing.assert_close(result, expected)

In [9]:
csr_SPMM_normalized(indptr, indices, features, norm="none", algorithm=3, use_cache=False, do_transpose_a=False)

tensor([[1., 2.],
        [1., 0.],
        [1., 2.]], device='cuda:0')

In [13]:
A = torch.sparse_csr_tensor(indptr, indices, torch.ones_like(indices)).to_dense().to(torch.float32)
B = features

In [14]:
A

tensor([[0., 1., 1.],
        [1., 0., 0.],
        [0., 1., 1.]], device='cuda:0')

In [15]:
B

tensor([[1., 0.],
        [0., 1.],
        [1., 1.]], device='cuda:0')

In [18]:
A.T @ B

tensor([[0., 1.],
        [2., 1.],
        [2., 1.]], device='cuda:0')